version: "3.2"
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3.13"
    network_mode: "host"
    volumes:
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    command: /usr/local/bin/etcd --auto-compaction-mode=revision --auto-compaction-retention=1000
    restart: on-failure
  st_keeper0:
    image: "infinivision/stolon-keeper"
    network_mode: "host"
    env_file: keeper0_env.txt
    volumes:
      - type: bind
        source: /opt/data/stolon-data0
        target: /stolon-data
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    restart: on-failure
  st_keeper1:
    image: "infinivision/stolon-keeper"
    network_mode: "host"
    env_file: keeper1_env.txt
    volumes:
      - type: bind
        source: /opt/data/stolon-data1
        target: /stolon-data
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    restart: on-failure
  st_keeper2:
    image: "infinivision/stolon-keeper"
    network_mode: "host"
    env_file: keeper2_env.txt
    volumes:
      - type: bind
        source: /opt/data/stolon-data2
        target: /stolon-data
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    restart: on-failure
  haproxy:
    image: "infinivision/haproxy"
    network_mode: "host"
    volumes:
      - type: bind
        source: /opt/data/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    restart: on-failure
  postgres_exporter:
    image: "wrouesnel/postgres_exporter"
    network_mode: "host"
    env_file: postgres_exporter_env.txt
    volumes:
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    restart: on-failure
  prometheus:
    image: "quay.io/prometheus/prometheus"
    network_mode: "host"
    user: "0"
    volumes:
      - type: bind
        source: /opt/data/prometheus-data
        target: /prometheus
      - type: bind
        source: /opt/data/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: /usr/share/zoneinfo/Asia/Shanghai
        target: /etc/localtime
    restart: on-failure
