apiVersion: infinivision.com/v1alpha1
kind: CitusCluster
metadata:
  name: example-cituscluster
spec:
  # Add fields here
  keeper:
    size: 3
    image: infinivision/stolon-keeper
    imagePullPolicy: IfNotPresent
  proxy:
    masterPort: 5432
    standbyPort: 5433
    type: NodePort