// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusCluster":       schema_pkg_apis_infinivision_v1alpha1_CitusCluster(ref),
		"github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusClusterSpec":   schema_pkg_apis_infinivision_v1alpha1_CitusClusterSpec(ref),
		"github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusClusterStatus": schema_pkg_apis_infinivision_v1alpha1_CitusClusterStatus(ref),
	}
}

func schema_pkg_apis_infinivision_v1alpha1_CitusCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CitusCluster is the Schema for the citusclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusClusterSpec", "github.com/infinivision/citus-operator/pkg/apis/infinivision/v1alpha1.CitusClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_infinivision_v1alpha1_CitusClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CitusClusterSpec defines the desired state of CitusCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_infinivision_v1alpha1_CitusClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CitusClusterStatus defines the observed state of CitusCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
